variables:
  IMAGE_NAME: myrealjay/ecwa
  IMAGE_TAG: quiz-1.0
stages:          # List of stages for jobs, and their order of execution
  #- test
  - build
  - deploy

build:   # This job runs in the test stage.
  stage: build    # It only starts when the job in the build stage completes successfully.
  image: docker:latest
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - echo "Building the project"
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@51.20.31.23 " 
      docker login -u $DOCKER_USER -p $DOCKER_PASS &&
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d -p 8000:8000 $IMAGE_NAME:$IMAGE_TAG"


